# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 欣园
subtitle:
description: 即使我们是笼中鸟</br>我们也与鸟笼的主人共享一套宇宙常数</br>即使我们是梦中花</br>我们也与做梦者共享一套底层逻辑</br> ——哇嘁《走修》
keywords: 个人博客,个人网站,ubuntu,linux,lxd,windows,python
author: Anshan
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.lpxin.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:











theme_config:
  # ---------------------------------------------------------------
  # Site Information Settings
  # See: https://theme-next.org/docs/getting-started/
  # ---------------------------------------------------------------

  favicon:
    small: /images/favicon16.ico
    medium: /images/favicon32.ico
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    #since: 2015

    # Icon between year and copyright info.
    icon:
      # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
      # `heart` is recommended with animation in red (#ff0000).
      name: heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#ff0000"
    # If not defined, `author` from Hexo main config will be used.
    copyright:

    powered:
      # Hexo link (Powered by Hexo).
      enable: false
      # Version info of Hexo after Hexo link (vX.X.X).
      version: false

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: false
      # Version info of NexT after scheme info (vX.X.X).
      version: false

    # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
    # http://www.beian.miit.gov.cn
    beian:
      enable: true
      icp: 皖ICP备17027266号-2



  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  # You can set a language value if you prefer a translated version of CC license.
  # CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
  # Valid values of language: deed.zh, deed.fr, deed.de, etc.
  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true
    language: zh-CN


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  # External url should start with http:// or https://
  menu:
    home: / || home
    #about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
    淘宝券: http://www.lpxin.com || barcode

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true



  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  #scheme: Gemini
  
  # Blog rolls
  links_icon: link
  links_title: 暖暖QWQ
  links_layout: block
  #links_layout: inline
  links:
    淘宝优惠: http://www.lpxin.com

  # Sidebar Avatar
  avatar:
    # In theme directory (source/images): /images/avatar.gif
    # In site directory (source/uploads): /uploads/avatar.gif
    # You can also use other linking images.
    url: /images/user.png

  social:
    GitHub: https://github.com/Anshan-pl || github


  sidebar:
    # Sidebar Position.
    #position: left
    position: right

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    #width: 300

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post

    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
    offset: 12
    # Enable sidebar on narrow view (only for Muse | Mist).
    onmobile: true


  back2top:
    enable: true
    # Back to top in sidebar.
    sidebar: false
    # Scroll percent label in b2t button.
    scrollpercent: true

  reward:
    wechatpay: /images/wx.jpg
    alipay: /images/zfb.jpg
    #bitcoin: /images/bitcoin.png

  baidu_push: true

  # Valine
  # You can get your appid and appkey from https://leancloud.cn
  # More info available at https://valine.js.org
  valine:
    enable: true # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
    appid: HxKvdWq6f55yfUWVn1gOacK7-gzGzoHsz # your leancloud application appid
    appkey: wIt5foUx4PwHx1pbgGfD58Ai # your leancloud application appkey
    notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: 欢迎留言，神评走一波~ # comment box placeholder
    avatar: mm # gravatar style
    guest_info: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    language: zh-cn # language, available values: en, zh-cn
    visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
    comment_count: true # if false, comment count will only be displayed in post page, not in home page

  #Show number of visitors to each article.
  # You can visit https://leancloud.cn to get AppID and AppKey.
  leancloud_visitors:
    enable: false
    app_id: HxKvdWq6f55yfUWVn1gOacK7-gzGzoHsz
    app_key: wIt5foUx4PwHx1pbgGfD58Ai
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in leancloud counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
    security: false
    betterPerformance: true

  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false